#!/bin/bash

suffix=$(cat /dev/urandom | tr -dc 'a-zA-Z' | fold -w 8 | head -n 1)
export VM_NAME=${VM_NAME:-"$WAY-$ENVIRONMENT_OS-$OPENSTACK_VERSION-$suffix"}
export NET_NAME="$VM_NAME"
export POOL_NAME=${POOL_NAME:-$WAY}
_bridge_name="${WAY:0:2}-${ENVIRONMENT_OS:0:1}-$suffix"
export BRIDGE_NAME=${BRIDGE_NAME:-$_bridge_name}
export DISK_SIZE=${DISK_SIZE:-'128'}
export NET_DRIVER=${NET_DRIVER:-'e1000'}
