#!/bin/bash -x

# if [[ -z "$RHEL_USER" || -z "$RHEL_PASSWORD" ]] ; then
#   echo "ERROR: provide RHEL_USER and RHEL_PASSWORD env variables to subscribe image"
#   exit -1
# fi

image=$1
# openstack=$2
# if [[ -z "$image" ]] ; then
#   echo "ERROR: the first argument is expected to be the path to image"
#   exit -1
# fi

# if [[ -z "$openstack" ]] ; then
#   echo "ERROR: the second argument is expected to be the openstack version newton/ocata"
#   exit -1
# fi

if [[ ! -f $image ]] ; then
  echo "ERROR: failed to find $image"
  exit -1
fi

# dst_image=${3:-${image}}
# dst_image_size=${4:-'100G'}
dst_image=${2:-${image}}
dst_image_size=${3:-'100G'}

export LIBGUESTFS_BACKEND=direct
if [[ "$image" != "$dst_image" ]] ; then
  qemu-img create -f qcow2 $dst_image $dst_image_size
  virt-resize --expand /dev/sda1 $image $dst_image
fi

# ###################
# Registartion and adding repos are done in test-execution workflow
#####################
# common_repos="rhel-7-server-rpms rhel-7-server-extras-rpms rhel-7-server-rh-common-rpms rhel-ha-for-rhel-7-server-rpms rhel-7-server-cert-rpms"
# if [[ "$openstack" == 'newton' ]] ; then
#   enable_repo="10"
# elif [[ "$openstack" == 'ocata' ]] ; then
#   enable_repo="11"
# else
#   echo "ERROR: unsupported OS $openstack"
#   exit 1
# fi
# common_repos+=" rhel-7-server-openstack-${enable_repo}-rpms"
# common_repos+=" rhel-7-server-openstack-${enable_repo}-devtools-rpms"

# enable_repos_opts=""
# for i in $common_repos ; do
#   enable_repos_opts+=" --enable=${i}"
# done

# virt-customize -a $dst_image \
#   --run-command 'xfs_growfs /' \
#   --sm-credentials ${RHEL_USER}:password:${RHEL_PASSWORD} --sm-register --sm-attach auto \
#   --run-command "subscription-manager repos ${enable_repos_opts}" \
#   --run-command 'sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config' \
#   --run-command 'systemctl enable sshd' \
#   --root-password password:qwe123QWE \
#   --selinux-relabel
virt-customize -a $dst_image \    
    --run-command 'xfs_growfs /' \
    --run-command 'sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config' \
    --run-command 'systemctl enable sshd' \
    --root-password password:qwe123QWE \
    --run-command 'useradd -m stack -s /bin/bash' \
    --run-command 'echo "stack:qwe123QWE" | chpasswd' \
    --run-command 'echo "stack ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/stack' \
    --ssh-inject root:file:/home/jenkins/.ssh/id_rsa.pub \
    --ssh-inject stack:file:/home/jenkins/.ssh/id_rsa.pub \
    --selinux-relabel
