#!/bin/bash

function juju-status() {
  juju status $juju_model_arg --format yaml $@
}

function juju-status-tabular() {
  juju status $juju_model_arg --format tabular $@
}

function juju-status-json() {
  juju status $juju_model_arg --format json $@
}

function juju-machines-tabular() {
  juju machines $juju_model_arg --format tabular $@
}

function juju-deploy() {
  juju deploy $juju_model_arg "$@"
}

function juju-add-unit () {
  juju add-unit $juju_model_arg "$@"
}

function juju-remove-unit () {
  juju remove-unit $juju_model_arg "$@"
}

function juju-expose () {
  juju expose $juju_model_arg "$@"
}

function juju-add-relation () {
  juju add-relation $juju_model_arg "$@"
}

function juju-remove-relation () {
  juju remove-relation $juju_model_arg "$@"
}

function juju-ssh () {
  juju ssh $juju_model_arg "$@"
}

function juju-scp () {
  juju scp $juju_model_arg "$@"
}

function juju-add-machine () {
  juju add-machine $juju_model_arg "$@"
}

function juju-remove-machine () {
  juju remove-machine $juju_model_arg "$@"
}

function juju-resolved () {
  juju resolved $juju_model_arg "$@"
}

function get_machines_index_by_service() {
  local srv=$1
  juju-status-tabular $srv | awk "/^$srv\//{print \$4}"
}
