#!/bin/bash

function check_k8s_cluster() {
  tmpf=`mktemp`
  cat <<EOM > $tmpf
#!/bin/bash -ex
set -o pipefail

echo "INFO: cluster state"
kubecctl get all --all-namespaces

echo "INFO: check NS create/delete"
kubectl create ns jujuns
sleep 2
kubectl get ns jujuns -o yaml
kubectl delete ns jujuns
sleep 2
if kubectl get ns jujuns -o yaml ; then
  echo "ERROR: NS was not deleted"
fi

kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
wget -nv https://storage.googleapis.com/kubernetes-helm/helm-v2.9.0-linux-amd64.tar.gz
tar -xvf helm-v2.9.0-linux-amd64.tar.gz
mv linux-amd64/helm /usr/bin/
helm init
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller", "automountServiceAccountToken": true}}}}'
helm init --service-account tiller --upgrade
# 'helm version' hangs if it's not ready
sleep 30
helm version
kubectl get pods --all-namespaces
helm repo update
helm install --name wordpress --set mariadb.master.persistence.enabled=false --set persistence.enabled=false stable/wordpress
sleep 90
kubectl get pods
kubectl get svc wordpress
if ! kubectl get svc wordpress | awk '/wordpress/{print $3}' | grep -v 'Running' ; then
  echo "ERROR: wordpress is not up!"
  exit 1
fi
EOM

  $SCP_CMD $tmpf ${SSH_USER}@${kubectl_ip}:check_k8s.sh
  rm $tmpf
  $SSH_CMD ${SSH_USER}@${kubectl_ip} "sudo /bin/bash check_k8s.sh"

  # this is needed if we want to enable persistence
  # ? helm repo add nfs-provisioner https://raw.githubusercontent.com/IlyaSemenov/nfs-provisioner-chart/master/repo
  # ? helm install --name nfs-provisioner --namespace nfs-provisioner nfs-provisioner/nfs-provisioner && sleep 5
  # ? kubectl patch storageclass local-nfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
}

