#!/bin/bash

job_prefix="jc8"
juju_controller_name="${job_prefix}-cloud"
export juju_model_arg="-m ${juju_controller_name}:default"

poolname="${job_prefix}images"
net_driver=${net_driver:-e1000}
nname="$job_prefix"
addr="10.0.15"
nname_vm="${job_prefix}_vm"
addr_vm="10.0.16"

mac_base='52:54:15:10:00'
mac_base_vm='52:54:16:11:00'

# juju controller
juju_cont_idx='99'
# compute
comp_count=1
comp_1_idx='30'
# openstack components (controllers + rabbit + db)
cont_0_idx='10'
# contrail controllers
cont_1_idx='20'
cont_2_idx='21'
cont_3_idx='22'
