#!/bin/bash

export AWS_FLAGS="--region us-west-2"

#export SSH_USER=ec2-user
# CentOS 7.4.1708 - HVM
# us-east-2 : ami-a0fddfc5
# us-west-2 : ami-82bd4ffa
#export IMAGE_ID=ami-82bd4ffa

# official images https://wiki.centos.org/Cloud/AWS
export SSH_USER=centos
export IMAGE_ID=ami-a042f4d8

export IFCONFIG_PATH=/usr/sbin
export IF1=eth0
export IF2=eth1

function create_iface() {
  local iface=$1
  shift
  local ssh=$@
  mac=`$ssh "/usr/sbin/ip link" 2>/dev/null | grep -A 1 " $iface:" | tail -1 | awk '{print $2}'`
  echo "INFO: create if script for iface=$iface with mac=$mac"
  if_path="/etc/sysconfig/network-scripts/ifcfg-$iface"
  $ssh "sudo bash -c 'echo \"BOOTPROTO=dhcp\" > $if_path && echo \"DEVICE=$iface\" > $if_path && echo \"HWADDR=$mac\" > $if_path && echo \"ONBOOT=yes\" > $if_path && echo \"TYPE=Ethernet\" > $if_path && echo \"USERCTL=no\" > $if_path && echo \"DEFROUTE=no\" > $if_path && ifup $iface'"
}
