#!/bin/bash

export AWS_FLAGS="--region us-west-2"
export SSH_USER=ubuntu
# ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20180426.2
# us-west-2 : ami-22741f5a
export IMAGE_ID=ami-22741f5a
export IFCONFIG_PATH=/sbin
export IF1=ens3
export IF2=ens4
export IF3=ens5
export IF4=ens6
export IF5=ens7

function create_iface() {
  local iface=$1
  shift
  local ssh=$@

  # bionic
  mac=`$ssh "ip link" 2>/dev/null | grep -A 1 " $iface:" | tail -1 | awk '{print $2}'`
  echo "INFO: create if script for iface=$iface with mac=$mac"
  if_path="/etc/netplan/50-cloud-init.yaml"
  cat <<EOF | $ssh
sudo bash -c 'echo "        $iface:" >> $if_path'
sudo bash -c 'echo "            dhcp4: true" >> $if_path'
sudo bash -c 'echo "            match:" >> $if_path'
sudo bash -c 'echo "                macaddress: $mac" >> $if_path'
sudo bash -c 'echo "            set-name: $iface" >> $if_path'
sudo netplan apply
EOF
}
