# Creating Treasuremap EC2 host
- hosts: localhost
  vars: 
    instance_type: t2.2xlarge
    volume_size: 300
    akraino_group: treasuremap_host
    project_variables: "vars/akraino.yaml"
  vars_files:
    - "{{ project_variables }}"
  connection: local
  roles:
    - roles/akraino_deploy_ec2_instance

# Deploying Akraino Regional Controller on existing EC2 host
- hosts: rc_host
  vars:
    project_variables: "vars/akraino.yaml"
  vars_files:
    - "{{ project_variables }}"
  become: yes
  roles:
  - roles/install_docker_ce
  - roles/akraino_deploy_rc

# Waiting for airship deployment is finished and download the log

- hosts: treasuremap_host
  vars:
    akraino_group: treasuremap_host
    project_variables: "vars/akraino.yaml"
  vars_files:
    - "{{ project_variables }}"
  tasks:
  - name: Wait until the file /tmp/DEPLOYMENT_COMPLETED is present (it takes a few hours)
    wait_for:
      host: "{{inventory_hostname}}"
      path: /tmp/DEPLOYMENT_COMPLETED

  - name: Download deployment log    
    fetch:
      src: /tmp/airship-in-a-bottle.sh.output.log
      dest: ../../logs/airship-in-a-bottle.output.log      
      flat: true


# Deleting Akraino EC2 instances and cleanup inventory and dynamic variables

- hosts: rc_host
  vars:
    akraino_group: rc_host
    project_variables: "vars/akraino.yaml"
  vars_files:
    - "{{ project_variables }}"
  roles:
  - roles/akraino_terminate_ec2_instance

- hosts: treasuremap_host
  vars:
    akraino_group: treasuremap_host
    project_variables: "vars/akraino.yaml"
  vars_files:
    - "{{ project_variables }}"
  roles:
  - roles/akraino_terminate_ec2_instance

- hosts: localhost
  vars:
    project_variables: "vars/akraino.yaml"
  vars_files:
    - "{{ project_variables }}"
  roles:
  - roles/akraino_cleanup_ec2
