#!/bin/bash -e

famy_file="${BASH_SOURCE[0]}"
famy_dir="$(dirname $famy_file)"
source $famy_dir/../common/functions-aws
source $famy_dir/../common/functions-contrail
source $famy_dir/../common/functions-contrail-R4
